trigger: 
  branches:
    include:
      - feature/*
      - main

pool:
  name: SelfAgent_RK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  OverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

stages:
  - stage: Init
    displayName: Initial
    jobs:
      - job: Install
        displayName: Terraform Install
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
      - job: Init
        displayName: Terraform Init
        dependsOn: Install
        steps:
          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(config_path)'
              backendServiceArm: 'SC_RK'
              backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
              backendAzureRmResourceGroupName: 'DoNotDeleteRg'
              backendAzureRmStorageAccountName: 'donotdeletestorage555'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'rkstest.tfstate'

  - stage: Plan
    displayName: Plan
    dependsOn: Init
    jobs:
      - job: plan
        displayName: Terraform Plan
        steps:
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(config_path)'
              environmentServiceNameAzureRM: 'SC_RK'
              environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'

