trigger:
  branches:
    include:
      - feature/*
      - main

pool:
  name: SelfAgent_RK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  OverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

parameters:
  - name: runInitPlan
    displayName: Run Init + Plan?
    type: boolean
    default: true

  - name: validation
    displayName: Manual validation?
    type: boolean
    default: false

  - name: runApply
    displayName: Run Apply?
    type: boolean
    default: false

stages:

# ----------------------
# Stage 1: Build
# ----------------------
- stage: Build
  displayName: Build Stage (Init + Plan)
  condition: eq('${{ parameters.runInitPlan }}', true)
  jobs:
    - job: terraform_init_plan
      displayName: Terraform Init + Plan
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(config_path)'
            backendServiceArm: 'SC_RK'
            backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
            backendAzureRmResourceGroupName: 'DoNotDeleteRg'
            backendAzureRmStorageAccountName: 'donotdeletestorage555'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'rkstest.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(config_path)'
            environmentServiceNameAzureRM: 'SC_RK'
            environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
# ----------------------
# Stage 2: Deploy
# ----------------------
- stage: Deploy
  displayName: Deploy Stage (Manual Validation and Apply)
  dependsOn: Build
  condition: eq('${{ parameters.runApply }}', true)
  jobs:

    - job: manual_validation
      displayName: Manual Validation
      condition: eq('${{ parameters.validation }}', true)
      pool: server
      steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'ravikumarsheokand1985@gmail.com'
            instructions: 'Check and approve'

    - job: terraform_apply
      displayName: Terraform Apply
      dependsOn: manual_validation
      condition: or(eq('${{ parameters.validation }}', false), succeeded('manual_validation'))
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(config_path)'
            backendServiceArm: 'SC_RK'
            backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
            backendAzureRmResourceGroupName: 'DoNotDeleteRg'
            backendAzureRmStorageAccountName: 'donotdeletestorage555'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'rkstest.tfstate'
            commandOptions: '-reconfigure'  # <== Fix included here too

        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(config_path)'
            environmentServiceNameAzureRM: 'SC_RK'
            environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'