trigger: 
  branches:
    include:
      - feature/*
      - main

pool:
  name: SelfAgent_RK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  OverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

parameters:
  - name: initplan
    displayName: Run Init + Plan?
    type: string
    values:
      - true
      - false

  - name: validation
    displayName: Manual Validation?
    type: string
    values:
      - true
      - false

  - name: runapply
    displayName: Run Apply?
    type: string
    values:
      - true
      - false

stages:
  - stage: InitPlan
    displayName: Init + Plan
    condition: eq('${{ parameters.initplan }}', 'true')
    jobs:
      - job: TerraformInit
        displayName: Terraform Init
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(config_path)'
              backendServiceArm: 'SC_RK'
              backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
              backendAzureRmResourceGroupName: 'DoNotDeleteRg'
              backendAzureRmStorageAccountName: 'donotdeletestorage555'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'rkstest.tfstate'

      - job: TerraformPlan
        displayName: Terraform Plan
        dependsOn: TerraformInit  # This job waits for Init to finish successfully
        condition: succeeded()
        steps:
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(config_path)'
              environmentServiceNameAzureRM: 'SC_RK'
              environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'

  - stage: ManualValidation
    displayName: Manual Validation
    dependsOn: InitPlan
    condition: and(succeeded(), eq('${{ parameters.validation }}', 'true'))  # Only run if validation is 'true'
    jobs:
      - job: Manual_validation
        displayName: Manual Validation
        steps:
          - task: ManualValidation@1  # Explicit versioning to use task 1.0
            inputs:
              notifyUsers: 'erasheo25@gmail.com'
              instructions: 'Check and approve'

  - stage: Apply
    displayName: Apply
    condition: and(succeeded(), eq('${{ parameters.runapply }}', 'true'))  # Only run if runapply is 'true'
    jobs:
      - job: ApplyJob
        displayName: Terraform Apply
        dependsOn: Init
        steps:
          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(config_path)'
              environmentServiceNameAzureRM: 'SC_RK'
              environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
