trigger:
  branches:
    include:
      - feature/*
      - main

pool:
  name: SelfAgent_RK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  OverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

parameters:
  - name: Build
    displayName: Build (Run Init,Validate,Plan) ?
    type: boolean
    default: false

  - name: Deploy
    displayName: Deploy(Manual validation + Apply) ?
    type: boolean
    default: false

stages:

# ----------------------
# Stage 1: Build
# ----------------------
- stage: Build
  displayName: Build Stage (Init + Plan)
  condition: eq('${{ parameters.Build }}', true)
  jobs:
# Job 1
    - job: terraform_init_fmt_validate
      displayName: Terraform Init + Fmt + Validate
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: Terraform Format
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(config_path)'
            commandOptions: 'fmt'
            outputTo: 'console'
            environmentServiceNameAzureRM: 'SC_RK'
            environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
        - task: TerraformTask@5
          displayName: Terraform Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(config_path)'
# Job 2
    - job: terraform_init_plan
      dependsOn: terraform_init_fmt_validate
      displayName: Terraform Init + Plan
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(config_path)'
            backendServiceArm: 'SC_RK'
            backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
            backendAzureRmResourceGroupName: 'DoNotDeleteRg'
            backendAzureRmStorageAccountName: 'donotdeletestorage555'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'rkstest.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(config_path)'
            environmentServiceNameAzureRM: 'SC_RK'
            environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
# ----------------------
# Stage 2: Deploy
# ----------------------

- stage: Deploy
  displayName: Deploy Stage (Manual Validation and Apply)
  dependsOn: Build
  condition: eq('${{ parameters.Deploy }}', true)
  jobs:

    - job: manual_validation
      displayName: Manual Validation
      pool: server
      steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'erashe25@gmail.com'
            instructions: 'Check and approve'

    - job: terraform_apply
      displayName: Terraform Apply
      dependsOn: manual_validation
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(config_path)'
            backendServiceArm: 'SC_RK'
            backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
            backendAzureRmResourceGroupName: 'DoNotDeleteRg'
            backendAzureRmStorageAccountName: 'donotdeletestorage555'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'rkstest.tfstate'
            commandOptions: '-reconfigure'

        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(config_path)'
            environmentServiceNameAzureRM: 'SC_RK'
            environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'