trigger: none

pool: 
 name: SelfAgent_RK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  OverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

steps:
- task: TerraformInstaller@1
  displayName: install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(config_path)'
    backendServiceArm: 'SC_RK'
    backendAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'
    backendAzureRmResourceGroupName: 'DoNotDeleteRg'
    backendAzureRmStorageAccountName: 'donotdeletestorage555'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'rkstest.tfstate'

- task: TerraformTask@5
  displayName: plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(config_path)'
    environmentServiceNameAzureRM: 'SC_RK'
    environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'

- task: TerraformTask@5
  displayName: apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(config_path)'
    environmentServiceNameAzureRM: 'SC_RK'
    environmentAzureRmOverrideSubscriptionID: '$(OverrideSubscriptionID)'